### ISSUE TITLE
Chomments 

### ISSUE THREAD

**Issue by christinahedges** [rodluger/mapping_stellar_surfaces#6]
# Paper 1

- [x] "and we assume the stellar surface does not vary in time[, (i.e. that spots do not evolve, and there is no differential rotation)]."

    _Thanks._

- [x] "light curve may be expressed as a weighted sum of the disk-integrated intensity of each of the spherical harmonics as they rotate about that same axis. [\cite{starry}]"

    _Done._

- [x] _"the vast majority of the surface modes lie at least partly in the null space."_ From the name and your above description, "null-space" is a binary, null or not null, observable or unobservable. Can you explain how something can be partially null?

    _Removed the "partially null" bit._

- [x] I don't feel strongly, but fig 3 isn't ideal, why are there black arrows indicating rank and nullity, shouldn't you just have a legend showing that blue is rank, and have a third line for nullity? black lines and text are confusing.

   _If you don't feel too strongly, I'm going to keep it._

- [x] "Even with an extremely restrictive prior, it may be difficult—if not impossible—to learn the properties of the spots from these light curves." Paper 2 states it's possible. Do you perhaps mean: "Even with an extremely restrictive prior, it may be difficult—if not impossible—to learn the **exact maps** from these light curves."? 

    _Clarified that this statement applies to individual light curves._

- [x] Fig 7: When you say -identical- stars, please can you add in words that this means both identical map, and at the same rotational phase.

    _Done._

- [x] "enough information in a large ensemble [(e.g. N unique light curves)] to independently"

    _Thanks._

- [x] Section 3.1 Can you explain very briefly that knowing the distance from Gaia does not solve this problem.

    _Clarified this._

- [x] "light curvesare also" -> "light curves are also"

    _Thanks._

# Paper 2

- [x] Introduction has no motivation for why people are interested in stellar variability. Could add a trite paragraph to the top of the introduction. This could also be pretty copy pasted from paper 1 I imagine?
Talking points:
    -  Used to infer rotation rates, which in turn helps identify ages (gyrchronology papers)
    -  Used to infer activity, and differential rotation [e.g. https://iopscience.iop.org/article/10.3847/1538-4357/aae77e, https://iopscience.iop.org/article/10.3847/1538-4357/ab7384 and lots of others]
    - With mixed results (Aigrain study?) (add stuff from the ADAP proposal here)
    -  Stellar variability hampers planet searches (e.g. https://iopscience.iop.org/article/10.3847/0004-6256/151/2/43, https://www.aanda.org/articles/aa/full_html/2019/01/aa34166-18/aa34166-18.html)
    - Therefore it is important to model stellar variability. 

- [x] I understand this is personal preference but I find it very helpful as a reader for the introduction to lay out the sections in the paper. E.g. "In Section X we introduce our model, in Section Y we calibrate the model and demonstrate it's efficacy in this regime...in Section Z we show that the model is useful for inference..." right now I am struggling to quickly understand what I should be learning from each section. 

    _Is this sufficient?_

![image](https://user-images.githubusercontent.com/9323819/106324072-84317a80-6246-11eb-9d40-2f4d87921a24.png)

- [x] Eqn 24: what is blackboard "l"? ("I"?) It's not been introduced in the text and it isn't 100% obvious from context, because of the blackboard (random variable of inclination? can you spell that out in words)

    _Done. Thanks._

- [x] Sec 2.3 doesn't have the nice visual of lines with long periods being normalized and "pinched" in the middle. This might be a conscious choice, but i do like find that figure illustrates the problem very nicely. 

    _I moved that figure to Paper 1._ 👏 

- [x] Section 2.3 if this is in paper 1 can you just cut it down to "see paper 1"?

    _The expression for the covariance of a normalized process is not in paper 1 -- only a heads up that it's an issue and that we'll discuss it in detail in paper 2._

- [x] Section 2, can you make the hyperparameter distribution choice a subsection, so that it's really called out and not buried. 

    _I mention the hyperparameters twice: in Equation (13) and again in the "Summary" section in Equation (30). Is that sufficient?_

- [x] Hyper parameter distribution, Can you add some fluff/story time to talk about how a beta distribution is well motivated because 1) sun has active latitudes 2) it can be either isotropic or active latitudes 3) it has a little extra fitting power because it's symmetric around latitude = 0 degrees , which we see in the sun 4) add up models to get any distribution you want anyway.

    _Great point. Done._

- [x] Section 2.5, can you add a sentence to the beginning that the example is there to show the reader X (shortcomings of GP?)

    _That section isn't meant to show the shortcomings of the GP (though I do discuss them!) It really is just meant to be a concrete example of the GP and to show that it does in fact work._

- [x] Section 2.5 "But before we dive in," [to calibrating the model] or [to demonstrating the model]?

- [x] Section 3 "In this section, we will show that, fortunately, the non-Gaussianity of the distribution is not in general an issue when doing inference with our GP" why is this? Is it just at high dimension it doesn't make a difference? or are you just lucky? if you know, can you add a sentence at the end saying so.

    _Honestly I don't know why it works so well. I think it's something about the central limit theorem and the fact that, like you said, the high dimensionality of the problem helps. But AFAIK this is not fully understood even by statisticians. So I'd rather not speculate too much about this._

- [x] Section 3 states posteriors are unbiased, but fig 7 a few pages down is then very biased, and you say paper 1 states that it will always be biased. Is section 3 is stating that if you model surfaces at l=30, l=15 will produce unbiased spherical harmonics, but not necessarily unbiased hyper parameters? 

    _I wouldn't say Figure 7 is "very biased"! That figure shows draws from the posterior distribution for the mode and variance shown in Figure 6. Those are correct to within about 2.5 and 1 sigma, respectively. The difference between the orange curve and the blue curves in Figure 7 is about 1 or 2 sigma, so this is all expected for a single realization of the noise. There's always bias when you make a single measurement (or consider a single ensemble) -- the point is that on average it's unbiased. I show this in Figure 9 (ish) and in Figure S23, where I consider an ensemble of 1000 light curves -- in that case, it's clear the blue distributions are converging to the orange one! Does that make sense?_

    _EDIT: I added a footnote describing why it's unbiased, and how inference on a larger ensemble shows the distributions converging._

**Comment by rodluger** [comment]
@chedges All done with these. Can you look them over? And let me know if you have more. Thanks!

**Comment by rodluger** [comment]
@christinahedges All done with these. Can you look them over? And let me know if you have more. Thanks!

**Comment by christinahedges** [comment]
# JOSS paper

- [x] “(averaged over many trials)” —> “(averaged over many trials to account for noise/numerical instabilities/something)”

- [x] “This is the approximate time (on a typical modern laptop) taken to compute 
the GP covariance matrix” Is this something you need only once per e.g. inclination? or do I have to calculate that at every step? 

    _Once per hyperparameter vector (including inclination if you're not explicitly marginalizing over it._

- [x] “Examples” link is broken (but exists in docs)
