### ISSUE TITLE
Random inclinations are the magic?

### ISSUE THREAD

**Issue by jradavenport** [rodluger/mapping_stellar_surfaces#9]
In paper 2 you say that ensembles of 50+ stars w/ presumably random inclinations let you get the actual information about the underlying spot properties (w/ assumptions about similarity of the underlying sample).

How well can you do w/ LOTS of independent observations of a single star over a long time? Can you still back out the inclination to 10%?

Also cool papers! I look forward to trying the new GP out (when I can get Theano to play ball on my M1 Mac again! LOL) Brett & I were always interested in modeling ensembles of transiting systems w/ different impact parameters to constrain spot latitude distributions, and this seems like the right tool to do that probabilistically.

**Comment by rodluger** [comment]
Good question! At a single inclination you're stuck with a single (very small) set of modes that aren't in the null space. So the question is whether the covariance structure in those modes is sufficient to constrain all the spot parameters and the inclination. My gut feeling is that there will be some degeneracies still, but you might be able to learn quite a bit. If you had good priors on the spot parameters -- and the only thing you didn't know was the inclination -- then it's a no-brainer: you could infer it with the ~10% uncertainty we mentioned in the paper.

We're going to deal with time variability in more detail in the next paper, so this is totally something we could look at!
